# Generated by Django 3.0.3 on 2020-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babymon', '0002_remove_led_on_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='on_until',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
