# Generated by Django 3.0.3 on 2020-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babymon', '0003_led_on_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='all_leds',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
