# Generated by Django 3.0.3 on 2020-02-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babymon', '0004_led_all_leds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='all_leds',
            field=models.IntegerField(),
        ),
    ]
