# Generated by Django 3.0.3 on 2020-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babymon', '0005_auto_20200218_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='all_leds',
        ),
        migrations.AddField(
            model_name='led',
            name='noleds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
